tools:
  - changed-files:
    - any-glob-to-any-file: src/app/tools/**

ui:
  - changed-files:
    - any-glob-to-any-file: src/components/**

github:
  - changed-files:
    - any-glob-to-any-file: .github/**

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - package.json
      - pnpm-lock.yaml

tests:
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.test.ts"
      - "**/*.test.tsx"
      - "**/*.spec.ts"
      - "**/*.spec.tsx"

documentation:
  - changed-files:
    - any-glob-to-any-file: "**/*.md"
