coverage:
  paths:
    - coverage/lcov.info

comment:
  if: is_pull_request

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}

diff:
  target: 80%
  datastores:
    - artifact://${GITHUB_REPOSITORY}
