coverage:
  acceptable: current >= 80% && diff >= 0%
  badge:
    path: docs/coverage.svg
  paths:
    - coverage/lcov.info
push:
  if: is_default_branch

comment:
  if: is_pull_request

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
