coverage:
  coverage:
    acceptable: current >= 80% && diff >= 0%
  paths:
    - coverage/lcov.info

comment:
  if: is_pull_request

report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
